name: Build

on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # 
      - name: Set Up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      # 
      - name: Check Source
        uses: actions/checkout@v2

      - name: Get dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go get -v -t -d ./...

      - name: Build And Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go test -v -timeout=60s -race
          go build -race

      - name: Install Linter
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.26.0

      - name: Run Linter
        run: $GITHUB_WORKSPACE/golangci-lint run --print-issued-lines --out-format=github-actions 